# 海康威视相机参数配置文件

hik_camera_driver:
  ros__parameters:
    # 相机连接参数
    camera_ip: ""        # 相机IP地址，如果为空则使用序列号连接
    camera_serial: "00F26632041"                  # 使用序列号连接
    topic_name: "/image_raw"           # 图像话题名称
    auto_reconnect: true               # 是否自动重连
    reconnect_interval: 5              # 重连间隔(秒)
    
    # 相机参数
    frame_rate: 30.0                   # 帧率
    exposure_time: 1000.0              # 曝光时间(微秒)
    gain: 1.0                          # 增益值
    pixel_format: "bgr8"               # 像素格式
    
    # 图像参数
    image_width: 640                   # 图像宽度
    image_height: 480                  # 图像高度
    image_encoding: "bgr8"             # 图像编码格式
